name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
  workflow_dispatch:

env:
  RUBY: "2.7" # TODO switch to 3.1 when Cloudflare Pages supports it too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ env.RUBY }}"
          bundler-cache: true

      - run: bundle exec jekyll build
      - run: bundle exec jekyll doctor

      - name: Run html-proofer
        run: bundle exec htmlproofer ./_site --allow-hash-href --assume-extension --check-external-hash --check-favicon --check-img-http --check-opengraph --disable-external --empty-alt-ignore --internal-domains "expo.getbootstrap.com"

      - name: Upload docs
        uses: actions/upload-artifact@v3
        if: github.repository == 'twbs/bootstrap-expo' && github.ref == 'refs/heads/main'
        with:
          name: docs
          path: ./_site/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.repository == 'twbs/bootstrap-expo' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./_site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site/
